### PR TITLE
Update the setup creation

### PR DESCRIPTION
**Pull request by leonardocarreras**
The setup was deprecated and did not comply with PEP 517, then now we are using a `pyproject.toml` and a `setup.cfg` to generate the installable files.

### CODE REVIEW

**Review by stv0g — APPROVED** [review]
Thanks @leonardocarreras :)

It looks good to me. However, I think it would be a bit nicer to have everything in the `pyproject.toml` file like we do it for VILLASnode here:

https://github.com/VILLASframework/node/blob/master/python/pyproject.toml

But if you prefer to keep it separate, we can also merge it as is.

**Comment by stv0g** [comment]
Please make sure your commits are `Signed-off-by`.
See: https://github.com/VILLASframework/dataprocessing/pull/4/checks?check_run_id=17368896810

Also let me know if you need access to pypi.org to publish a new release of the package.

**Comment by leonardocarreras** [comment]
I will see if I can make it work all in `pyproject.toml`, I think it will be good if it follows the convention.

I will do the `Signed-off-by` (used the GPG signature only, my bad).

**Comment by leonardocarreras** [comment]
Fixed the signature problem, soon next will try the `toml`

**Comment by leonardocarreras** [comment]
@stv0g thanks for the comments, I think they are now addressed and the code seems to work in the virtual environment.

The only doubt remaining for me would be if the email `acs-software` is still operative, and/or if @dinkelbachjan & @m-mirz  would like a different thing in the metadata associated with their names

**Comment by leonardocarreras** [comment]
About pypi.org I am not very familiar with the process. I just finished with the set up of an account, the username is the same as here.

The changes are not very big but maybe the update in the metadata is important enough.

**Review by stv0g — APPROVED** [review]

**Pull request merged**
